#!/usr/bin/env bash

# test if curl/wget is installed
if hash curl 2>&- ; then
    CMD="curl -s -o"
elif hash wget 2>&- ; then
    CMD="wget -q -O"
else
   echo "You need to have curl or wget installed."
   exit 1
fi

$CMD /usr/local/bin/modman https://raw.github.com/colinmollenhour/modman/master/modman

chmod +x /usr/local/bin/modman

echo "Done. Modman installed in /usr/local/bin/modman"
